application: dantube
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /signin
  script: urls.application
  secure: always

- url: /signup
  script: urls.application
  secure: always

- url: /admin/.*
  login: admin
  script: urls.application

- url: /.*
  script: urls.application

libraries:
- name: webapp2
  version: 2.5.1
- name: jinja2
  version: 2.6
- name: PIL
  version: 1.1.7